schema_version: 1

context:
  name: plotly-resampler
  version: 0.11.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/plotly_resampler-${{ version }}.tar.gz
  sha256: e3f9ceeb5749de9a85d39755f50711a7d6a28eb1b284da250251c8896ccc1cfd

build:
  number: 0
  noarch: python
  skip: py>=400 or match(python, ">=2,<3")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - plotly >=5.5.0,<7.0.0
    - dash >=2.11.0
    - if: match(python, "<3.13")
      then: pandas >=1
    - if: match(python, ">=3.13")
      then: pandas >=2.2.3
    - if: match(python, "<3.11")
      then: numpy >=1.14
    - if: match(python, ">=3.11") and match(python, "<3.13")
      then: numpy >=1.24
    - if: match(python, ">=3.13")
      then: numpy >=2.0
    - orjson >=3.10.0,<4.0.0
    - tsdownsample >=0.1.3
  run_constraints:
    - flask_cors >=4.0.2,<5.0.0
    - python-kaleido 0.2.1.*

tests:
  - python:
      imports:
        - plotly_resampler
      pip_check: true

about:
  summary: Visualizing large time series with plotly
  license: MIT
  license_file: recipe/LICENSE
  homepage: https://github.com/predict-idlab/plotly-resampler
  documentation: https://predict-idlab.github.io/plotly-resampler/

extra:
  recipe-maintainers:
    - darynwhite
    - jvdd
    - thewchan
