conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: "2"
bot:
  automerge: true
  inspection: hint-all
  check_solvable: true
  run_deps_from_wheel: true
conda_install_tool: pixi
conda_build_tool: rattler-build
